# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  pipelines:
  - pipeline: tiggered   # Name of the pipeline resource
    source: activator # Name of the triggering pipeline

trigger:
    branches:
      include:
      - master
      
pr:
- none
  
pool:
    vmImage: 'ubuntu-latest'

steps:
- script: echo Merged to staging branch!
  displayName: 'Begin deploy process'